name: Reusable Deploy

on:
    workflow_call:
        inputs:
            enviroment:
                required: true
                type: string
        secrets:
            PASSWORD:
                required: true

        outputs:
          application-url:
            value: ${{ jobs.jobs1.outputs.application-url }}
jobs:
    jobs1:
      if: inputs.enviroment == 'production'
      runs-on: ubuntu-latest

      steps:
        - name: step1
          run: |
           echo production-deploy
           echo $PASSWORD