name: Reusable Workflow Use
on:
    push:

jobs:
    job-caller: 
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            enviroment: production
        secrets:
            PASSWORD: ${{ secrets.PASSWORD }}
    test:
        needs: job-caller
        runs-on: ubuntu-latest
        steps:
          - run: echo "${{ needs.job-caller.outputs.application-url }}"
        