name: triggering-workflows
on: 
  workflow_dispatch:

    #  schedule:
#    - cron: "*/5 * * * *"
env:
    VAR1: Victor
jobs:
    jobname:
        runs-on: ubuntu-latest
        steps:
            - name: commad1
              run: echo "meu nome é $VAR"