name: triggering-workflows
on: 
  push

    #  schedule:
#    - cron: "*/5 * * * *"

env:
    VAR1: Victor
jobs:
    jobname2:
        runs-on: ubuntu-latest
        steps:
            - name: commad1
              run: ls -a
    jobname:
        concurrency:
            group: job-group-1
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: commad1
              run: echo meu nome é $VAR
    